apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: kusama-alert-rules
      rules:
        {{- range .Values.wallets }}
        - alert: LowKusamaFunds{{ .address }}
          expr: kusama_account_funds{address="{{ .address }}"} < {{ .threshold }}
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Low funds alert for address {{ .address }}"
            description: "{{ .address }} has less than {{ .threshold }} KSM funds."
        {{- end }}
